---
- name: Install git on OpenSuse
  zypper:
   name: git
   state: latest

- name: Clone Prelim Exam branch on Opensuse
  git:
    repo: '{{ prelim_exam }}'
    dest: ./prelim-exam
    version: prelim-exam
# tasks file for roles/suse_gitclone