---
- name: Installing Dependencies on OpenSuse
  zypper:
   name:
    - apache2
    - gcc
    - glibc
    - gd
    - perl
    - php7
    - apache2-mod_php7
    - unzip
   state: latest

- name: Enable php7
  shell: 'a2enmod php7'

- name: Creating nagios group
  group:
   name: nagios
   state: present

- name: Creating nagios group
  group:
   name: nagcmd
   state: present

- name: Creating nagios group
  group:
   name: nagadmin
   state: present

- name: Creating Nagios User
  user:
   name: nagios
   comment: nagios user
   group: nagadmin

- name: Adding wwwrun user group for External Command
  user:
   name: wwwrun
   group: nagadmin
   append: yes

- name: Creating downloads directory
  file:
   path: /downloads
   state: directory

- name: Downloading Nagios
  get_url:
   url: http://prdownloads.sourceforge.net/sourceforge/nagios/nagios-4.2.1.tar.gz
   dest: /downloads

- name: Extracting Nagios Core
  unarchive:
   src: /downloads/nagios-4.2.1.tar.gz
   dest: /downloads
   remote_src: yes

- name: Creating Virtual Host Directory
  file:
   path: /etc/httpd/conf.d
   state: directory

- name: Configuring Nagios Script
  shell: ./configure --with-command-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/httpd/conf.d
  args:
   chdir: /downloads/nagios-4.2.1

- name: Compiling Nagios Core
  make:
   chdir: /downloads/nagios-4.2.1
   target: all

- name: Installing Binaries
  make:
   chdir: /downloads/nagios-4.2.1
   target: install

- name: Installing init script
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-init

- name: Installing sample config files
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-config

- name: Installing set permissions
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-commandmode

- name: Installing Nagios web interface
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-webconf

- name: Installing pip for htpasswd
  zypper:
   name: python3-pip
   state: latest

- name: Installing htpasswd module
  pip:
   name: passlib
   state: latest

- name: Creating nagiosadmin account
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: '{{ nagadmin_pass }}'

- name: Restarting Apache
  service:
   name: apache2
   state: reloaded

- name: Start Nagios service
  shell: '/etc/init.d/nagios start'

# tasks file for roles/suse_nagios